'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
    
#Region "Функциональные возможности автосохранения My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property AccessToken() As String
        Get
            Return CType(Me("AccessToken"),String)
        End Get
        Set
            Me("AccessToken") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Notification3() As Boolean
        Get
            Return CType(Me("Notification3"),Boolean)
        End Get
        Set
            Me("Notification3") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Notification4() As Boolean
        Get
            Return CType(Me("Notification4"),Boolean)
        End Get
        Set
            Me("Notification4") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Notification8() As Boolean
        Get
            Return CType(Me("Notification8"),Boolean)
        End Get
        Set
            Me("Notification8") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Notification9() As Boolean
        Get
            Return CType(Me("Notification9"),Boolean)
        End Get
        Set
            Me("Notification9") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Notification61() As Boolean
        Get
            Return CType(Me("Notification61"),Boolean)
        End Get
        Set
            Me("Notification61") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Notification62() As Boolean
        Get
            Return CType(Me("Notification62"),Boolean)
        End Get
        Set
            Me("Notification62") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FF597DA3")>  _
    Public Property AccentColor() As Global.System.Windows.Media.Color
        Get
            Return CType(Me("AccentColor"),Global.System.Windows.Media.Color)
        End Get
        Set
            Me("AccentColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property Theme() As Integer
        Get
            Return CType(Me("Theme"),Integer)
        End Get
        Set
            Me("Theme") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property MessageSendType1() As Boolean
        Get
            Return CType(Me("MessageSendType1"),Boolean)
        End Get
        Set
            Me("MessageSendType1") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property MessageSendType2() As Boolean
        Get
            Return CType(Me("MessageSendType2"),Boolean)
        End Get
        Set
            Me("MessageSendType2") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property Font() As Integer
        Get
            Return CType(Me("Font"),Integer)
        End Get
        Set
            Me("Font") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("8192")>  _
    Public Property Volume() As Integer
        Get
            Return CType(Me("Volume"),Integer)
        End Get
        Set
            Me("Volume") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Invisible() As Boolean
        Get
            Return CType(Me("Invisible"),Boolean)
        End Get
        Set
            Me("Invisible") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Background() As String
        Get
            Return CType(Me("Background"),String)
        End Get
        Set
            Me("Background") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0.15")>  _
    Public Property BackgroundOpacity() As Double
        Get
            Return CType(Me("BackgroundOpacity"),Double)
        End Get
        Set
            Me("BackgroundOpacity") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property IsBackground() As Boolean
        Get
            Return CType(Me("IsBackground"),Boolean)
        End Get
        Set
            Me("IsBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property IsSetActivity() As Boolean
        Get
            Return CType(Me("IsSetActivity"),Boolean)
        End Get
        Set
            Me("IsSetActivity") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property CheckLink() As Boolean
        Get
            Return CType(Me("CheckLink"),Boolean)
        End Get
        Set
            Me("CheckLink") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property MarkMessageInvisible() As Boolean
        Get
            Return CType(Me("MarkMessageInvisible"),Boolean)
        End Get
        Set
            Me("MarkMessageInvisible") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property NotificationH() As Integer
        Get
            Return CType(Me("NotificationH"),Integer)
        End Get
        Set
            Me("NotificationH") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property NotificationV() As Integer
        Get
            Return CType(Me("NotificationV"),Integer)
        End Get
        Set
            Me("NotificationV") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property IsSpeak() As Boolean
        Get
            Return CType(Me("IsSpeak"),Boolean)
        End Get
        Set
            Me("IsSpeak") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
    Public Property SpeakRate() As Integer
        Get
            Return CType(Me("SpeakRate"),Integer)
        End Get
        Set
            Me("SpeakRate") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property SpellCheck() As Boolean
        Get
            Return CType(Me("SpellCheck"),Boolean)
        End Get
        Set
            Me("SpellCheck") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Notification40() As Boolean
        Get
            Return CType(Me("Notification40"),Boolean)
        End Get
        Set
            Me("Notification40") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FF2A3345")>  _
    Public Property NColor3() As String
        Get
            Return CType(Me("NColor3"),String)
        End Get
        Set
            Me("NColor3") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FF2A3345")>  _
    Public Property NColor4() As String
        Get
            Return CType(Me("NColor4"),String)
        End Get
        Set
            Me("NColor4") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FF008A00")>  _
    Public Property NColor8() As String
        Get
            Return CType(Me("NColor8"),String)
        End Get
        Set
            Me("NColor8") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FF647687")>  _
    Public Property NColor9() As String
        Get
            Return CType(Me("NColor9"),String)
        End Get
        Set
            Me("NColor9") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FF2A3345")>  _
    Public Property NColor61() As String
        Get
            Return CType(Me("NColor61"),String)
        End Get
        Set
            Me("NColor61") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FF2A3345")>  _
    Public Property NColor62() As String
        Get
            Return CType(Me("NColor62"),String)
        End Get
        Set
            Me("NColor62") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FF2A3345")>  _
    Public Property NColor40() As String
        Get
            Return CType(Me("NColor40"),String)
        End Get
        Set
            Me("NColor40") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Version() As String
        Get
            Return CType(Me("Version"),String)
        End Get
        Set
            Me("Version") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Culture() As String
        Get
            Return CType(Me("Culture"),String)
        End Get
        Set
            Me("Culture") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property MD5() As String
        Get
            Return CType(Me("MD5"),String)
        End Get
        Set
            Me("MD5") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property InTaskbar() As Boolean
        Get
            Return CType(Me("InTaskbar"),Boolean)
        End Get
        Set
            Me("InTaskbar") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property IsClosed() As Boolean
        Get
            Return CType(Me("IsClosed"),Boolean)
        End Get
        Set
            Me("IsClosed") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property PlayerNotInTaskBar() As Boolean
        Get
            Return CType(Me("PlayerNotInTaskBar"),Boolean)
        End Get
        Set
            Me("PlayerNotInTaskBar") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property VideoPlayerTopMost() As Boolean
        Get
            Return CType(Me("VideoPlayerTopMost"),Boolean)
        End Get
        Set
            Me("VideoPlayerTopMost") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property MusicPlayerSnap() As Boolean
        Get
            Return CType(Me("MusicPlayerSnap"),Boolean)
        End Get
        Set
            Me("MusicPlayerSnap") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property SearchSelectIndex() As Integer
        Get
            Return CType(Me("SearchSelectIndex"),Integer)
        End Get
        Set
            Me("SearchSelectIndex") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property UseYandexImage() As Boolean
        Get
            Return CType(Me("UseYandexImage"),Boolean)
        End Get
        Set
            Me("UseYandexImage") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property YandexToday() As Date
        Get
            Return CType(Me("YandexToday"),Date)
        End Get
        Set
            Me("YandexToday") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property isMicroVKGroup() As Boolean
        Get
            Return CType(Me("isMicroVKGroup"),Boolean)
        End Get
        Set
            Me("isMicroVKGroup") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Voice() As String
        Get
            Return CType(Me("Voice"),String)
        End Get
        Set
            Me("Voice") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property MRandom() As Boolean
        Get
            Return CType(Me("MRandom"),Boolean)
        End Get
        Set
            Me("MRandom") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property MRepeat() As Boolean
        Get
            Return CType(Me("MRepeat"),Boolean)
        End Get
        Set
            Me("MRepeat") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Share() As Boolean
        Get
            Return CType(Me("Share"),Boolean)
        End Get
        Set
            Me("Share") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property DialogStyle() As Integer
        Get
            Return CType(Me("DialogStyle"),Integer)
        End Get
        Set
            Me("DialogStyle") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property runMinimized() As Boolean
        Get
            Return CType(Me("runMinimized"),Boolean)
        End Get
        Set
            Me("runMinimized") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property speak3() As Boolean
        Get
            Return CType(Me("speak3"),Boolean)
        End Get
        Set
            Me("speak3") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property speak4() As Boolean
        Get
            Return CType(Me("speak4"),Boolean)
        End Get
        Set
            Me("speak4") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property speak40() As Boolean
        Get
            Return CType(Me("speak40"),Boolean)
        End Get
        Set
            Me("speak40") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property speak8() As Boolean
        Get
            Return CType(Me("speak8"),Boolean)
        End Get
        Set
            Me("speak8") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property speak9() As Boolean
        Get
            Return CType(Me("speak9"),Boolean)
        End Get
        Set
            Me("speak9") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property speak61() As Boolean
        Get
            Return CType(Me("speak61"),Boolean)
        End Get
        Set
            Me("speak61") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property speak62() As Boolean
        Get
            Return CType(Me("speak62"),Boolean)
        End Get
        Set
            Me("speak62") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property SpeakChatMessage() As Boolean
        Get
            Return CType(Me("SpeakChatMessage"),Boolean)
        End Get
        Set
            Me("SpeakChatMessage") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property SpeakMessage() As Boolean
        Get
            Return CType(Me("SpeakMessage"),Boolean)
        End Get
        Set
            Me("SpeakMessage") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
    Public Property SpeakVolume() As Integer
        Get
            Return CType(Me("SpeakVolume"),Integer)
        End Get
        Set
            Me("SpeakVolume") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property hideTabs() As Boolean
        Get
            Return CType(Me("hideTabs"),Boolean)
        End Get
        Set
            Me("hideTabs") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property isButton() As Boolean
        Get
            Return CType(Me("isButton"),Boolean)
        End Get
        Set
            Me("isButton") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("800, 640")>  _
    Public Property windowsSize() As Global.System.Drawing.Size
        Get
            Return CType(Me("windowsSize"),Global.System.Drawing.Size)
        End Get
        Set
            Me("windowsSize") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property isWindowsSize() As Boolean
        Get
            Return CType(Me("isWindowsSize"),Boolean)
        End Get
        Set
            Me("isWindowsSize") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property dsAvatar() As Boolean
        Get
            Return CType(Me("dsAvatar"),Boolean)
        End Get
        Set
            Me("dsAvatar") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property dsAvatarOut() As Boolean
        Get
            Return CType(Me("dsAvatarOut"),Boolean)
        End Get
        Set
            Me("dsAvatarOut") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#33000000")>  _
    Public Property dsColor() As String
        Get
            Return CType(Me("dsColor"),String)
        End Get
        Set
            Me("dsColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#66000000")>  _
    Public Property dsColorOut() As String
        Get
            Return CType(Me("dsColorOut"),String)
        End Get
        Set
            Me("dsColorOut") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#33647687")>  _
    Public Property dsColorDark() As String
        Get
            Return CType(Me("dsColorDark"),String)
        End Get
        Set
            Me("dsColorDark") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#3387794E")>  _
    Public Property dsColorOutDark() As String
        Get
            Return CType(Me("dsColorOutDark"),String)
        End Get
        Set
            Me("dsColorOutDark") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#000000")>  _
    Public Property dsFontColor() As String
        Get
            Return CType(Me("dsFontColor"),String)
        End Get
        Set
            Me("dsFontColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#000000")>  _
    Public Property dsFontColorOut() As String
        Get
            Return CType(Me("dsFontColorOut"),String)
        End Get
        Set
            Me("dsFontColorOut") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FFFFFF")>  _
    Public Property dsFontColorDark() As String
        Get
            Return CType(Me("dsFontColorDark"),String)
        End Get
        Set
            Me("dsFontColorDark") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FFFFFF")>  _
    Public Property dsFontColorOutDark() As String
        Get
            Return CType(Me("dsFontColorOutDark"),String)
        End Get
        Set
            Me("dsFontColorOutDark") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property microVKHelp() As Boolean
        Get
            Return CType(Me("microVKHelp"),Boolean)
        End Get
        Set
            Me("microVKHelp") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property saveProfile() As Boolean
        Get
            Return CType(Me("saveProfile"),Boolean)
        End Get
        Set
            Me("saveProfile") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FF76608A")>  _
    Public Property NColor41() As String
        Get
            Return CType(Me("NColor41"),String)
        End Get
        Set
            Me("NColor41") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property speak41() As Boolean
        Get
            Return CType(Me("speak41"),Boolean)
        End Get
        Set
            Me("speak41") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Notification41() As Boolean
        Get
            Return CType(Me("Notification41"),Boolean)
        End Get
        Set
            Me("Notification41") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property SendSuccessfullyNotify() As Boolean
        Get
            Return CType(Me("SendSuccessfullyNotify"),Boolean)
        End Get
        Set
            Me("SendSuccessfullyNotify") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property SmilePanel() As Boolean
        Get
            Return CType(Me("SmilePanel"),Boolean)
        End Get
        Set
            Me("SmilePanel") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property FloatTopMost() As Boolean
        Get
            Return CType(Me("FloatTopMost"),Boolean)
        End Get
        Set
            Me("FloatTopMost") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property IsMediaKey() As Boolean
        Get
            Return CType(Me("IsMediaKey"),Boolean)
        End Get
        Set
            Me("IsMediaKey") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property IsTabBottom() As Boolean
        Get
            Return CType(Me("IsTabBottom"),Boolean)
        End Get
        Set
            Me("IsTabBottom") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property photoSize() As Integer
        Get
            Return CType(Me("photoSize"),Integer)
        End Get
        Set
            Me("photoSize") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property RunAsStartup() As Boolean
        Get
            Return CType(Me("RunAsStartup"),Boolean)
        End Get
        Set
            Me("RunAsStartup") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property OnlineWait() As Boolean
        Get
            Return CType(Me("OnlineWait"),Boolean)
        End Get
        Set
            Me("OnlineWait") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.MicroVK.MySettings
            Get
                Return Global.MicroVK.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
